services:
  app:
    build:
      context: .
    restart: unless-stopped
    image: node:22
    working_dir: /home/node/app
    ports:
      - "${PORT}:3000"
    volumes:
      - .:/home/node/app
      # - node_modules:/home/node/app/node_modules
    command: npm ci && npm run start
